import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBarComponents from '../components/NavBarComponents'
import FooterComponents from '../components/FooterComponents'
import SubscribeComponents from '../components/SubscribeComponents'
import EnquiryFormComponents from '../components/EnquiryFormComponents'
import AppFeaturesComponents from '../components/AppFeaturesComponents'
import GalleryComponents from '../components/GalleryComponents'
import RoundUpComponents from '../components/RoundUpComponents'
import WeComponents from '../components/WeComponents'
import BannerComponents from '../components/BannerComponents'
import FormTestComponents from '../components/FormTestComponents'




export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.4/dist/flowbite.min.css" />
        <script src="../path/to/flowbite/dist/flowbite.js" async></script>
        <script src="https://unpkg.com/flowbite@1.5.4/dist/flowbite.js" async></script>
        <script type="text/javascript"src="https://cdn.jsdelivr.net/npm/@emailjs/browser@3/dist/email.min.js"></script>

   



      </Head>
      <NavBarComponents></NavBarComponents>
      <BannerComponents></BannerComponents>
      <WeComponents></WeComponents>
      <RoundUpComponents></RoundUpComponents>
      <GalleryComponents></GalleryComponents>
      <AppFeaturesComponents></AppFeaturesComponents>
      {/* <FormTestComponents></FormTestComponents> */}
      <EnquiryFormComponents></EnquiryFormComponents>
      <SubscribeComponents></SubscribeComponents>
      <FooterComponents></FooterComponents>
      

    </div>
  )
}
